In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.linear_model import LinearRegression

In [5]:
lr = LinearRegression()

In [10]:
dataset= pd.read_csv("/Users/paruldiwakar/Desktop/codes/test_train/air_quality_index/Train.csv").values

In [11]:
dataset

array([[ 2.93416239e-01, -9.45598713e-01, -4.21105147e-01,
         4.06816021e-01,  5.25661832e-01, -8.21546666e+01],
       [-8.36084081e-01, -1.89228039e-01, -7.76402618e-01,
        -1.05383124e+00,  5.97996852e-01, -4.88979602e+01],
       [ 2.36425114e-01,  1.32836018e-01, -1.47722982e-01,
         6.99853963e-01, -1.87364163e-01,  7.72703707e+01],
       ...,
       [ 1.04417694e+00, -8.99206485e-01,  1.73039905e+00,
        -1.87105676e+00,  4.42519647e-01, -1.07510508e+02],
       [-1.26917290e+00, -5.05215916e-03,  1.85766873e+00,
        -1.08036482e+00,  7.36333937e-01, -4.73415578e+01],
       [-1.88400025e+00, -8.49427430e-01, -1.45227035e+00,
         4.88613076e-01,  1.45957580e+00, -1.15939003e+02]])

In [6]:
X_train = dataset[:,:-1]

In [7]:
y_train = dataset[:,-1]

In [8]:
X_test=pd.read_csv("/Users/paruldiwakar/Desktop/codes/test_train/air_quality_index/Test.csv").values

In [9]:
X_test

array([[ 1.01525387e+00,  2.07620944e+00, -2.66434820e-01,
        -2.41808820e+00, -9.80502790e-01],
       [-3.75021204e-01,  9.53184528e-01,  6.26719138e-01,
         7.04405750e-01, -3.55489211e-01],
       [-1.02445225e+00,  9.62991107e-01, -4.07942004e-01,
        -1.86127383e+00,  4.55201351e-01],
       ...,
       [ 5.54727647e-01,  1.76824345e+00, -8.97787210e-01,
        -1.19366107e+00,  3.40563374e-01],
       [-1.62717246e+00,  8.56470994e-01, -5.65729519e-04,
         6.29386649e-01,  4.53382144e-01],
       [ 1.39310499e-01,  5.31597186e-01, -8.53107053e-01,
         3.16920076e-02,  1.71489304e+00]])

In [10]:
lr.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [11]:
lr.predict(X_test).shape

(400,)

In [12]:
y_pred = lr.predict(X_test)

In [13]:
lr.score(X_train,y_train)

0.9660939669975616

In [14]:
lr.score(X_test,y_pred)

1.0

In [15]:
y_pred= pd.DataFrame(data = y_pred,columns =['target'])

In [130]:
y_pred.to_csv("air_quality_index.csv")

In [131]:
y_pred

         target
0    114.583689
1    118.012815
2    -21.739852
3    -43.936899
4    -95.914898
5    -44.507424
6    -75.566526
7     23.820835
8    173.835284
9    172.849290
10  -105.402312
11   -20.802023
12    -3.913238
13   122.999186
14    40.307884
15    45.712850
16  -189.628491
17    22.612545
18    11.641047
19   136.342143
20    64.916255
21   -61.988488
22  -108.194679
23    -7.412127
24   -58.523953
25    11.888978
26    29.237640
27   107.687579
28    24.146856
29   -26.105012
..          ...
370 -137.921702
371  -50.514772
372  -93.679380
373    8.816282
374  -14.604027
375  -62.851997
376  -16.465554
377 -172.962640
378 -122.791775
379   45.273898
380  -37.309931
381 -157.438494
382   87.498386
383   -0.320726
384  133.257842
385  -47.172209
386    2.574661
387  174.227519
388  170.930081
389   46.433357
390  -26.720651
391   59.632252
392  111.659113
393  -36.502767
394  -69.139053
395  -81.989000
396 -186.032535
397  125.292336
398   65.369841
399   57.059691

[400 rows x 1 columns]

In [135]:
pd.read_csv("/Users/paruldiwakar/Desktop/codes/air_quality_index.csv")

      id      target
0      0  114.583689
1      1  118.012815
2      2  -21.739852
3      3  -43.936899
4      4  -95.914898
5      5  -44.507424
6      6  -75.566526
7      7   23.820835
8      8  173.835284
9      9  172.849290
10    10 -105.402312
11    11  -20.802023
12    12   -3.913238
13    13  122.999186
14    14   40.307884
15    15   45.712850
16    16 -189.628491
17    17   22.612545
18    18   11.641047
19    19  136.342143
20    20   64.916255
21    21  -61.988488
22    22 -108.194679
23    23   -7.412127
24    24  -58.523953
25    25   11.888978
26    26   29.237640
27    27  107.687579
28    28   24.146856
29    29  -26.105012
..   ...         ...
370  370 -137.921702
371  371  -50.514772
372  372  -93.679380
373  373    8.816282
374  374  -14.604027
375  375  -62.851997
376  376  -16.465554
377  377 -172.962640
378  378 -122.791775
379  379   45.273898
380  380  -37.309931
381  381 -157.438494
382  382   87.498386
383  383   -0.320726
384  384  133.257842
385  385  -47.172209
386  386    2.574661
387  387  174.227519
388  388  170.930081
389  389   46.433357
390  390  -26.720651
391  391   59.632252
392  392  111.659113
393  393  -36.502767
394  394  -69.139053
395  395  -81.989000
396  396 -186.032535
397  397  125.292336
398  398   65.369841
399  399   57.059691

[400 rows x 2 columns]